language: node_js
node_js:
  - "node"

stages:
  - lint
  - build
cache: npm
jobs:
  include:
    - stage: build
      script:
        - npm run generate
        - cd dist
        - cp index.html 404.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist
        target_branch: master
        fqdn: cherm.io
        on:
          branch: develop
